forge "http://forge.puppetlabs.com"

mod 'fervid/secure_linux_cis', :latest
mod 'aboe/chrony'
mod 'camptocamp/augeas'
mod 'camptocamp/kmod'
mod 'camptocamp/postfix'
mod 'herculesteam/augeasproviders_core'
mod 'herculesteam/augeasproviders_grub'
mod 'herculesteam/augeasproviders_sysctl'
mod 'herculesteam/augeasproviders_shellvar'
mod 'herculesteam/augeasproviders_pam'
mod 'kemra102/auditd'
mod 'puppet/alternatives'
mod 'puppet/cron'
mod 'puppet/logrotate'
mod 'puppetlabs/augeas_core'
mod 'puppetlabs/firewall'
mod 'puppetlabs/mailalias_core'
mod 'puppetlabs/mount_core'
mod 'puppetlabs/ntp'
mod 'puppetlabs/reboot'
mod 'puppetlabs/stdlib'
